import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import { TestimonyButton } from '../components/questions';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>nonCnon</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading="Vous pensez avoir été victime d'harcèlement sexuel ?" message="" />
      <Slider slides={SliderData} />
      <TestimonyButton />
      <Instagram />
    </div>  
  );
}
